import type { Metadata } from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import styles from "./layout.module.css"
import {Header} from "../components/Header/Header";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ru">
        <body>
        <div className={`${styles.wrapper} ${geistSans.variable} ${geistMono.variable}`}>
            <Header/>
            <div className={styles.body}>
                {children}
            </div>
        </div>
        </body>
        </html>
    );
}
